/**
 * STM32F407ZGT6 HAL Template — main.c
 * Target: cortex-m4, 1024KB Flash, 192KB RAM
 * Generated by rabber mcu_init v1.3.2
 *
 * Minimal example: initialises the system clock and blinks an LED on PC13
 * (the built-in LED on most STM32 boards).
 */

#include <stdint.h>

/* ── Memory-mapped peripheral base addresses ── */
#define PERIPH_BASE           0x40000000U
#define AHB1PERIPH_BASE       (PERIPH_BASE + 0x00020000U)
#define GPIOC_BASE            (AHB1PERIPH_BASE + 0x0800U)

/* ── RCC registers ── */
#define RCC_BASE              (AHB1PERIPH_BASE + 0x3800U)
#define RCC_AHB1ENR           (*(volatile uint32_t *)(RCC_BASE + 0x30U))
#define RCC_AHB1ENR_GPIOCEN   (1U << 2)

/* ── GPIO registers ── */
#define GPIO_MODER            (*(volatile uint32_t *)(GPIOC_BASE + 0x00U))
#define GPIO_OTYPER           (*(volatile uint32_t *)(GPIOC_BASE + 0x04U))
#define GPIO_OSPEEDR          (*(volatile uint32_t *)(GPIOC_BASE + 0x08U))
#define GPIO_ODR              (*(volatile uint32_t *)(GPIOC_BASE + 0x14U))
#define GPIO_BSRR             (*(volatile uint32_t *)(GPIOC_BASE + 0x18U))

/* ── SysTick ── */
#define STK_BASE              0xE000E010U
#define STK_CTRL              (*(volatile uint32_t *)(STK_BASE + 0x00U))
#define STK_LOAD              (*(volatile uint32_t *)(STK_BASE + 0x04U))
#define STK_VAL               (*(volatile uint32_t *)(STK_BASE + 0x08U))
#define STK_CTRL_ENABLE       (1U << 0)
#define STK_CTRL_TICKINT      (1U << 1)
#define STK_CTRL_CLKSOURCE    (1U << 2)

/* ── System clock ── */
/* Default HSI = 16 MHz, no PLL — suitable for blink demo. */
#define SYSTEM_CLOCK_HZ       16000000U

/* ── Global tick counter ── */
static volatile uint32_t sys_ticks = 0;

/* ── Linker-defined symbols ── */
extern uint32_t _estack;      /* top of stack (defined in linker script) */
extern uint32_t _sidata, _sdata, _edata, _sbss, _ebss;

/* ── Forward declarations ── */
void SystemInit(void);
void SysTick_Handler(void);
static void SysTick_Config(uint32_t ticks);
void delay_ms(uint32_t ms);
int main(void);

/* ── Reset handler ── */
__attribute__((naked, noreturn))
void Reset_Handler(void) {
    uint32_t *src = &_sidata;
    uint32_t *dst = &_sdata;
    while (dst < &_edata) { *dst++ = *src++; }
    dst = &_sbss;
    while (dst < &_ebss) { *dst++ = 0; }

    SystemInit();
    main();
    while (1) { }
}

/* ── Default exception handlers ── */
__attribute__((weak, alias("Default_Handler")))
void NMI_Handler(void);
__attribute__((weak, alias("Default_Handler")))
void HardFault_Handler(void);
__attribute__((weak, alias("Default_Handler")))
void MemManage_Handler(void);
__attribute__((weak, alias("Default_Handler")))
void BusFault_Handler(void);
__attribute__((weak, alias("Default_Handler")))
void UsageFault_Handler(void);
__attribute__((weak, alias("Default_Handler")))
void SVC_Handler(void);
__attribute__((weak, alias("Default_Handler")))
void DebugMon_Handler(void);
__attribute__((weak, alias("Default_Handler")))
void PendSV_Handler(void);

void Default_Handler(void) {
    while (1) { }
}

/* ── Vector table ── */
__attribute__((section(".isr_vector")))
void (*const g_pfnVectors[])(void) = {
    (void (*)(void))(&_estack),          /* Initial stack pointer (top of RAM) */
    Reset_Handler,
    NMI_Handler,
    HardFault_Handler,
    MemManage_Handler,
    BusFault_Handler,
    UsageFault_Handler,
    0, 0, 0, 0,                        /* Reserved */
    SVC_Handler,
    DebugMon_Handler,
    0,                                  /* Reserved */
    PendSV_Handler,
    SysTick_Handler,
    /* ... additional IRQ handlers go here */
};

/* ── System initialisation ── */
void SystemInit(void) {
    /* Enable GPIOC clock */
    RCC_AHB1ENR |= RCC_AHB1ENR_GPIOCEN;

    /* Configure PC13 as push-pull output */
    GPIO_MODER   &= ~(3U << 26);   /* Clear mode bits */
    GPIO_MODER   |=  (1U << 26);   /* Output mode */
    GPIO_OTYPER  &= ~(1U << 13);   /* Push-pull */
    GPIO_OSPEEDR |=  (3U << 26);   /* High speed */

    /* Configure SysTick for 1 ms intervals */
    SysTick_Config(SYSTEM_CLOCK_HZ / 1000U);
}

/* ── SysTick configuration ── */
static inline void SysTick_Config(uint32_t ticks) {
    STK_LOAD = ticks - 1U;
    STK_VAL  = 0;
    STK_CTRL = STK_CTRL_CLKSOURCE | STK_CTRL_TICKINT | STK_CTRL_ENABLE;
}

/* ── SysTick interrupt handler ── */
void SysTick_Handler(void) {
    sys_ticks++;
}

/* ── Millisecond delay ── */
void delay_ms(uint32_t ms) {
    uint32_t start = sys_ticks;
    while ((sys_ticks - start) < ms) {
        /* spin */
    }
}

/* ── Main ── */
int main(void) {
    while (1) {
        /* Toggle PC13 (on-board LED) */
        GPIO_BSRR = (1U << 13);   /* LED off (set bit) — assuming active-low */
        delay_ms(500);
        GPIO_BSRR = (1U << (13 + 16)); /* LED on (reset bit) */
        delay_ms(500);
    }
    return 0;
}
