#!/usr/bin/env python3
"""Patch init.py — replace makefile_content, main_c_content, create_template, action_init."""
import re, sys

PATH = "plugins/mcu_init/python/init.py"
with open(PATH, "r") as f:
    text = f.read()

# ── locate key functions by signature ──
def find_func(text, name):
    """Return (start_idx, end_idx_exclusive, body) for a top-level function."""
    pattern = r'^def ' + re.escape(name) + r'\([^\n]*\n'
    m = re.search(pattern, text, re.MULTILINE)
    if not m:
        return None
    start = m.start()
    # find the next function or end of file
    next_def = re.search(r'^(def |class |# ──)', text[m.end():], re.MULTILINE)
    if next_def:
        end = m.end() + next_def.start()
    else:
        end = len(text)
    return start, end, text[start:end]

# ── 1. Replace makefile_content ──
r = find_func(text, 'makefile_content')
if r:
    s, e, old = r
    new_mk = '''def makefile_content(mcu: str, info: dict, hal_mode: bool = True) -> str:
    """Generate Makefile for the given MCU, optionally with HAL support."""
    upper = mcu.upper()
    cpu = info['cpu']
    march = info['march']
    fpu = info.get('fpu', None)
    flash_kb = info['flash_kb']
    ram_kb = info['ram_kb']
    series_upper = info.get('series_upper', 'STM32F4xx')
    device = info.get('device', 'stm32f407xx')
    startup = info.get('startup', 'startup_stm32f407xx')

    fpu_flags = f"-mfpu={fpu} -mfloat-abi=hard" if fpu else "-mfloat-abi=soft"
    linker_script = f"{upper}_FLASH.ld"

    if hal_mode:
        hal_incs = " ".join([
            f"-IDrivers/CMSIS/Core/Include",
            f"-IDrivers/CMSIS/Device/ST/{series_upper}/Include",
            f"-IDrivers/{series_upper}_HAL_Driver/Inc",
            f"-IInc",
        ])
        hal_objs_wildcard = f"$(wildcard Drivers/{series_upper}_HAL_Driver/Src/*.c)"
        hal_objs = f"$(patsubst Drivers/{series_upper}_HAL_Driver/Src/%.c,$(PROCESS_DIR)/hal_%.o,$(wildcard Drivers/{series_upper}_HAL_Driver/Src/*.c))"
        dev_src_wc = f"$(wildcard Drivers/CMSIS/Device/ST/{series_upper}/Source/Templates/*.c)"
        dev_objs = f"$(patsubst Drivers/CMSIS/Device/ST/{series_upper}/Source/Templates/%.c,$(PROCESS_DIR)/%.o,$(wildcard Drivers/CMSIS/Device/ST/{series_upper}/Source/Templates/*.c))"
        asm_src = f"Drivers/CMSIS/Device/ST/{series_upper}/Source/Templates/gcc/{startup}.s"
        asm_obj = f"$(PROCESS_DIR)/{startup}.o"
        define_chip = f"-D{upper} -D{device.upper()} -DUSE_HAL_DRIVER"
        src_dir = "Src"
        inc_dir = "Inc"
    else:
        hal_incs = "-Iinclude"
        hal_objs_wildcard = ""
        hal_objs = ""
        dev_src_wc = ""
        dev_objs = ""
        asm_src = ""
        asm_obj = ""
        define_chip = f"-D{upper}"
        src_dir = "src"
        inc_dir = "include"

    return f\'\'\'# Makefile for {upper} {\'HAL\' if hal_mode else \'Bare-Metal\'} Template
# Generated by rabber mcu_init v{VERSION}
# Target: {cpu} ({march}), {flash_kb}KB Flash, {ram_kb}KB RAM
# Mode: {\'HAL library\' if hal_mode else \'bare-metal (register-level)\'}

# ── Toolchain ──
CC      = arm-none-eabi-gcc
OBJCOPY = arm-none-eabi-objcopy
OBJDUMP = arm-none-eabi-objdump
SIZE    = arm-none-eabi-size
GDB     = arm-none-eabi-gdb

# ── Target MCU ──
MCU      = {upper}
CPU      = {cpu}
FPU      = {fpu if fpu else \'none\'}

# ── Directories ──
BUILD_DIR   = build
PROCESS_DIR = process
SRC_DIR     = {src_dir}
INC_DIR     = {inc_dir}
\'\'\' + (f\'\'\'

# ── HAL / CMSIS ──
HAL_DRV_DIR  = Drivers/{series_upper}_HAL_Driver
CMSIS_DIR    = Drivers/CMSIS
ASM_SRC      = {asm_src}
\'\'\' if hal_mode else "") + f\'\'\'

# ── Source files ──
C_SRCS   = $(wildcard $(SRC_DIR)/*.c)\'\'\' + (f" {hal_objs_wildcard} {dev_src_wc}" if hal_mode else "") + f\'\'\'
ASM_SRCS =\'\'\' + (f" {asm_src}" if hal_mode else " $(wildcard $(SRC_DIR)/*.s)") + f\'\'\'
OBJS     = $(C_SRCS:$(SRC_DIR)/%.c=$(PROCESS_DIR)/%.o) \\\\
           $(ASM_SRCS:$(SRC_DIR)/%.s=$(PROCESS_DIR)/%.o)\'\'\' + (f\'\'\' \\\\
           {hal_objs} \\\\
           {dev_objs} \\\\
           {asm_obj}\'\'\' if hal_mode else "") + f\'\'\'

# ── Output ──
TARGET   = $(BUILD_DIR)/{upper.lower()}
ELF      = $(TARGET).elf
HEX      = $(TARGET).hex
BIN      = $(TARGET).bin

# ── Compiler flags ──
CFLAGS  = -mcpu={cpu}
CFLAGS += -march={march}
CFLAGS += -mthumb
CFLAGS += {fpu_flags}
CFLAGS += -std=gnu11
CFLAGS += -Wall -Wextra -Werror
CFLAGS += -Os -g3 -ggdb
CFLAGS += -ffunction-sections -fdata-sections
CFLAGS += -fno-common
CFLAGS += {define_chip}

# ── Includes ──
INCLUDES = {hal_incs}

# ── Linker flags ──
LDSCRIPT = {linker_script}
LDFLAGS  = -T$(LDSCRIPT)
LDFLAGS += -mcpu={cpu}
LDFLAGS += -mthumb
LDFLAGS += {fpu_flags}
LDFLAGS += -specs=nosys.specs
LDFLAGS += -specs=nano.specs
LDFLAGS += -Wl,--gc-sections
LDFLAGS += -Wl,-Map=$(PROCESS_DIR)/output.map
LDFLAGS += -Wl,--print-memory-usage

# ── Phony targets ──
.PHONY: all clean flash

# ── Default ──
all: $(HEX) $(BIN)
	@echo ""
	@echo "[✓] 构建完成:"
	@$(SIZE) $(ELF)

# ── ELF ──
$(ELF): $(OBJS) $(LDSCRIPT)
	@mkdir -p $(BUILD_DIR)
	@echo "[LD]  $@"
	$(CC) $(OBJS) $(LDFLAGS) -o $@

# ── HEX ──
$(HEX): $(ELF)
	@echo "[HEX] $@"
	$(OBJCOPY) -O ihex $< $@

# ── BIN ──
$(BIN): $(ELF)
	@echo "[BIN] $@"
	$(OBJCOPY) -O binary $< $@

# ── Object files ──
$(PROCESS_DIR)/%.o: $(SRC_DIR)/%.c
	@mkdir -p $(PROCESS_DIR)
	@echo "[CC]  $<"
	$(CC) $(CFLAGS) $(INCLUDES) -c $< -o $@
\'\'\' + (f\'\'\'

# ── HAL object files ──
$(PROCESS_DIR)/hal_%.o: $(HAL_DRV_DIR)/Src/%.c
	@mkdir -p $(PROCESS_DIR)
	@echo "[CC]  $<"
	$(CC) $(CFLAGS) -I$(HAL_DRV_DIR)/Inc -IDrivers/CMSIS/Core/Include -IDrivers/CMSIS/Device/ST/{series_upper}/Include $(INCLUDES) -c $< -o $@

$(PROCESS_DIR)/{startup}.o: $(ASM_SRC)
	@mkdir -p $(PROCESS_DIR)
	@echo "[AS]  $<"
	$(CC) $(CFLAGS) -c $< -o $@
\'\'\' if hal_mode else f\'\'\'

$(PROCESS_DIR)/%.o: $(SRC_DIR)/%.s
	@mkdir -p $(PROCESS_DIR)
	@echo "[AS]  $<"
	$(CC) $(CFLAGS) -c $< -o $@
\'\'\') + f\'\'\'

# ── Clean ──
clean:
	rm -rf $(BUILD_DIR) $(PROCESS_DIR)
	@echo "[✓] 清理完成"

# ── Flash (via st-flash) ──
flash: $(BIN)
	st-flash --reset write $< 0x08000000
	@echo "[✓] 烧录完成"

# ── Debug ──
debug: $(ELF)
	$(GDB) $<
\'\'\'
'''
    text = text[:s] + new_mk + text[e:]
    print("[OK] makefile_content replaced")
else:
    print("[FAIL] makefile_content not found")

# ── 2. Replace main_c_content → main_c_hal_content + main_c_bare_content ──
r2 = find_func(text, 'main_c_content')
if r2:
    s, e, old = r2
    new_main = '''def main_c_hal_content(mcu: str, info: dict) -> str:
    """Generate main.c using STM32 HAL API."""
    upper = mcu.upper()
    cpu = info['cpu']
    flash_kb = info['flash_kb']
    ram_kb = info['ram_kb']
    device = info.get('device', 'stm32f407xx')
    series_upper = info.get('series_upper', 'STM32F4xx')

    return f"""/**
 * {upper} HAL Template — main.c
 * Target: {cpu}, {flash_kb}KB Flash, {ram_kb}KB RAM
 * Generated by rabber mcu_init v{VERSION}
 *
 * Blinks the on-board LED (PC13) using STM32 HAL library.
 */

#include "{device}.h"
#include "main.h"

/* Private variables */
static void SystemClock_Config(void);
static void MX_GPIO_Init(void);

/**
 * @brief  Main program
 */
int main(void)
{{
    /* Reset of all peripherals, Initializes the Flash interface and the Systick. */
    HAL_Init();

    /* Configure the system clock */
    SystemClock_Config();

    /* Initialize all configured peripherals */
    MX_GPIO_Init();

    /* Infinite loop */
    while (1)
    {{
        HAL_GPIO_TogglePin(GPIOC, GPIO_PIN_13);
        HAL_Delay(500);
    }}
}}

/**
 * @brief System Clock Configuration
 */
static void SystemClock_Config(void)
{{
    RCC_OscInitTypeDef RCC_OscInitStruct = {{0}};
    RCC_ClkInitTypeDef RCC_ClkInitStruct = {{0}};

    /* Configure the main internal regulator output voltage */
    __HAL_RCC_PWR_CLK_ENABLE();
    __HAL_PWR_VOLTAGESCALING_CONFIG(PWR_REGULATOR_VOLTAGE_SCALE1);

    /* Initializes the RCC Oscillators */
    RCC_OscInitStruct.OscillatorType = RCC_OSCILLATORTYPE_HSI;
    RCC_OscInitStruct.HSIState = RCC_HSI_ON;
    RCC_OscInitStruct.HSICalibrationValue = RCC_HSICALIBRATION_DEFAULT;
    RCC_OscInitStruct.PLL.PLLState = RCC_PLL_ON;
    RCC_OscInitStruct.PLL.PLLSource = RCC_PLLSOURCE_HSI;
    RCC_OscInitStruct.PLL.PLLM = 8;
    RCC_OscInitStruct.PLL.PLLN = 168;
    RCC_OscInitStruct.PLL.PLLP = RCC_PLLP_DIV2;
    RCC_OscInitStruct.PLL.PLLQ = 4;
    if (HAL_RCC_OscConfig(&RCC_OscInitStruct) != HAL_OK)
    {{
        while(1);
    }}

    /* Initializes the CPU, AHB and APB buses clocks */
    RCC_ClkInitStruct.ClockType = RCC_CLOCKTYPE_HCLK | RCC_CLOCKTYPE_SYSCLK
                                | RCC_CLOCKTYPE_PCLK1 | RCC_CLOCKTYPE_PCLK2;
    RCC_ClkInitStruct.SYSCLKSource = RCC_SYSCLKSOURCE_PLLCLK;
    RCC_ClkInitStruct.AHBCLKDivider = RCC_SYSCLK_DIV1;
    RCC_ClkInitStruct.APB1CLKDivider = RCC_HCLK_DIV4;
    RCC_ClkInitStruct.APB2CLKDivider = RCC_HCLK_DIV2;
    if (HAL_RCC_ClockConfig(&RCC_ClkInitStruct, FLASH_LATENCY_5) != HAL_OK)
    {{
        while(1);
    }}
}}

/**
 * @brief GPIO Initialization
 */
static void MX_GPIO_Init(void)
{{
    GPIO_InitTypeDef GPIO_InitStruct = {{0}};

    /* GPIO Ports Clock Enable */
    __HAL_RCC_GPIOC_CLK_ENABLE();

    /* Configure GPIO pin : PC13 */
    GPIO_InitStruct.Pin = GPIO_PIN_13;
    GPIO_InitStruct.Mode = GPIO_MODE_OUTPUT_PP;
    GPIO_InitStruct.Pull = GPIO_NOPULL;
    GPIO_InitStruct.Speed = GPIO_SPEED_FREQ_LOW;
    HAL_GPIO_Init(GPIOC, &GPIO_InitStruct);
}}

/**
 * @brief  This function is executed in case of error occurrence.
 */
void Error_Handler(void)
{{
    __disable_irq();
    while (1) {{ }}
}}
"""


def main_c_bare_content(mcu: str, info: dict) -> str:
    """Generate a bare-metal main.c (register-level, no HAL)."""
    upper = mcu.upper()
    cpu = info['cpu']
    flash_kb = info['flash_kb']
    ram_kb = info['ram_kb']

    return f"""/**
 * {upper} Bare-Metal Template — main.c
 * Target: {cpu}, {flash_kb}KB Flash, {ram_kb}KB RAM
 * Generated by rabber mcu_init v{VERSION}
 *
 * Minimal example: initialises the system clock and blinks an LED on PC13
 * using direct register access (no HAL dependency).
 */

#include <stdint.h>

/* ── Memory-mapped peripheral base addresses ── */
#define PERIPH_BASE           0x40000000U
#define AHB1PERIPH_BASE       (PERIPH_BASE + 0x00020000U)
#define GPIOC_BASE            (AHB1PERIPH_BASE + 0x0800U)

/* ── RCC registers ── */
#define RCC_BASE              (AHB1PERIPH_BASE + 0x3800U)
#define RCC_AHB1ENR           (*(volatile uint32_t *)(RCC_BASE + 0x30U))
#define RCC_AHB1ENR_GPIOCEN   (1U << 2)

/* ── GPIO registers ── */
#define GPIO_MODER            (*(volatile uint32_t *)(GPIOC_BASE + 0x00U))
#define GPIO_OTYPER           (*(volatile uint32_t *)(GPIOC_BASE + 0x04U))
#define GPIO_OSPEEDR          (*(volatile uint32_t *)(GPIOC_BASE + 0x08U))
#define GPIO_BSRR             (*(volatile uint32_t *)(GPIOC_BASE + 0x18U))

/* ── SysTick ── */
#define STK_BASE              0xE000E010U
#define STK_CTRL              (*(volatile uint32_t *)(STK_BASE + 0x00U))
#define STK_LOAD              (*(volatile uint32_t *)(STK_BASE + 0x04U))
#define STK_VAL               (*(volatile uint32_t *)(STK_BASE + 0x08U))
#define STK_CTRL_ENABLE       (1U << 0)
#define STK_CTRL_TICKINT      (1U << 1)
#define STK_CTRL_CLKSOURCE    (1U << 2)

#define SYSTEM_CLOCK_HZ       16000000U

static volatile uint32_t sys_ticks = 0;

/* ── Linker-defined symbols ── */
extern uint32_t _estack;
extern uint32_t _sidata, _sdata, _edata, _sbss, _ebss;

/* ── Forward declarations ── */
void SystemInit(void);
void SysTick_Handler(void);
static void SysTick_Config(uint32_t ticks);
void delay_ms(uint32_t ms);
int main(void);

/* ── Reset handler ── */
__attribute__((naked, noreturn))
void Reset_Handler(void) {{
    uint32_t *src = &_sidata;
    uint32_t *dst = &_sdata;
    while (dst < &_edata) {{ *dst++ = *src++; }}
    dst = &_sbss;
    while (dst < &_ebss) {{ *dst++ = 0; }}
    SystemInit();
    main();
    while (1) {{ }}
}}

/* ── Default exception handlers ── */
__attribute__((weak, alias("Default_Handler"))) void NMI_Handler(void);
__attribute__((weak, alias("Default_Handler"))) void HardFault_Handler(void);
__attribute__((weak, alias("Default_Handler"))) void MemManage_Handler(void);
__attribute__((weak, alias("Default_Handler"))) void BusFault_Handler(void);
__attribute__((weak, alias("Default_Handler"))) void UsageFault_Handler(void);
__attribute__((weak, alias("Default_Handler"))) void SVC_Handler(void);
__attribute__((weak, alias("Default_Handler"))) void DebugMon_Handler(void);
__attribute__((weak, alias("Default_Handler"))) void PendSV_Handler(void);

void Default_Handler(void) {{ while (1) {{ }} }}

/* ── Vector table ── */
__attribute__((section(".isr_vector")))
void (*const g_pfnVectors[])(void) = {{
    (void (*)(void))(&_estack),
    Reset_Handler, NMI_Handler, HardFault_Handler,
    MemManage_Handler, BusFault_Handler, UsageFault_Handler,
    0, 0, 0, 0, SVC_Handler, DebugMon_Handler, 0,
    PendSV_Handler, SysTick_Handler,
}};

void SystemInit(void) {{
    RCC_AHB1ENR |= RCC_AHB1ENR_GPIOCEN;
    GPIO_MODER   &= ~(3U << 26);
    GPIO_MODER   |=  (1U << 26);
    GPIO_OTYPER  &= ~(1U << 13);
    GPIO_OSPEEDR |=  (3U << 26);
    SysTick_Config(SYSTEM_CLOCK_HZ / 1000U);
}}

static void SysTick_Config(uint32_t ticks) {{
    STK_LOAD = ticks - 1U;
    STK_VAL  = 0;
    STK_CTRL = STK_CTRL_CLKSOURCE | STK_CTRL_TICKINT | STK_CTRL_ENABLE;
}}

void SysTick_Handler(void) {{ sys_ticks++; }}

void delay_ms(uint32_t ms) {{
    uint32_t start = sys_ticks;
    while ((sys_ticks - start) < ms) {{ }}
}}

int main(void) {{
    while (1) {{
        GPIO_BSRR = (1U << 13);
        delay_ms(500);
        GPIO_BSRR = (1U << (13 + 16));
        delay_ms(500);
    }}
    return 0;
}}
"""


# Compatibility: main_c_content is now main_c_bare_content
main_c_content = main_c_bare_content
'''
    text = text[:s] + new_main + text[e:]
    print("[OK] main_c_content replaced")
else:
    print("[FAIL] main_c_content not found")

# ── 3. Add HAL template helper functions before create_template ──
hal_templates = '''

# ── HAL template helpers ──

def hal_conf_content(mcu: str, info: dict) -> str:
    """Generate stm32f4xx_hal_conf.h template."""
    upper = mcu.upper()
    device = info.get('device', 'stm32f407xx')
    series_upper = info.get('series_upper', 'STM32F4xx')
    series_lower = series_upper.lower()

    modules = [
        ("ADC", "1"), ("CAN", "1"), ("CORTEX", "1"), ("CRC", "1"),
        ("CRYP", "1"), ("DAC", "1"), ("DCMI", "1"), ("DMA", "1"),
        ("ETH", "1"), ("FLASH", "1"), ("GPIO", "1"), ("HASH", "1"),
        ("HCD", "1"), ("I2C", "1"), ("I2S", "1"), ("IRDA", "1"),
        ("IWDG", "1"), ("PCD", "1"), ("PWR", "1"), ("RCC", "1"),
        ("RNG", "1"), ("RTC", "1"), ("SAI", "1"), ("SD", "1"),
        ("SMARTCARD", "1"), ("SPI", "1"), ("TIM", "1"), ("UART", "1"),
        ("USART", "1"), ("WWDG", "1"),
    ]
    mod_lines = "\\n".join([f"#define HAL_{m}_MODULE_ENABLED" for m, v in modules])

    return f"""/**
 * {series_upper} HAL Configuration File
 * Generated by rabber mcu_init v{VERSION}
 */
#ifndef __{series_upper}_HAL_CONF_H
#define __{series_upper}_HAL_CONF_H

#ifdef __cplusplus
extern "C" {{
#endif

/* ── Module activation ── */
{mod_lines}

/* ── Oscillator values (Hz) ── */
#define HSE_VALUE    8000000U
#define HSI_VALUE    16000000U
#define LSE_VALUE    32768U
#define LSI_VALUE    32000U
#define EXTERNAL_CLOCK_VALUE 12288000U

/* ── HAL tick priority (lower = higher priority) ── */
#define TICK_INT_PRIORITY 0x0FU

/* ── Enables 1ms SysTick ── */
#define USE_RTOS 0U

#include "{device}.h"

#ifdef __cplusplus
}}
#endif

#endif /* __{series_upper}_HAL_CONF_H */
"""


def hal_it_content(mcu: str, info: dict) -> str:
    """Generate stm32f4xx_it.c (interrupt handlers)."""
    series_upper = info.get('series_upper', 'STM32F4xx')
    device = info.get('device', 'stm32f407xx')
    series_lower = series_upper.lower()

    return f"""/**
 * {series_upper} Interrupt Handlers
 * Generated by rabber mcu_init v{VERSION}
 */
#include "{device}.h"
#include "{series_lower}_hal_conf.h"
#include "{series_lower}_it.h"

extern void Error_Handler(void);

/* ── SysTick Handler ── */
void SysTick_Handler(void)
{{
    HAL_IncTick();
}}

/* ── NMI Handler ── */
void NMI_Handler(void) {{ }}

/* ── HardFault Handler ── */
void HardFault_Handler(void)
{{
    while (1) {{ }}
}}

/* ── MemManage Handler ── */
void MemManage_Handler(void)
{{
    while (1) {{ }}
}}

/* ── BusFault Handler ── */
void BusFault_Handler(void)
{{
    while (1) {{ }}
}}

/* ── UsageFault Handler ── */
void UsageFault_Handler(void)
{{
    while (1) {{ }}
}}
"""


def hal_it_header_content(mcu: str, info: dict) -> str:
    """Generate stm32f4xx_it.h header."""
    series_upper = info.get('series_upper', 'STM32F4xx')
    series_lower = series_upper.lower()

    return f"""/**
 * {series_upper} Interrupt Handlers Header
 * Generated by rabber mcu_init v{VERSION}
 */
#ifndef __{series_upper}_IT_H
#define __{series_upper}_IT_H

#ifdef __cplusplus
extern "C" {{
#endif

void SysTick_Handler(void);
void NMI_Handler(void);
void HardFault_Handler(void);
void MemManage_Handler(void);
void BusFault_Handler(void);
void UsageFault_Handler(void);

#ifdef __cplusplus
}}
#endif

#endif /* __{series_upper}_IT_H */
"""


def hal_msp_content(mcu: str, info: dict) -> str:
    """Generate stm32f4xx_hal_msp.c (MCU Support Package)."""
    series_upper = info.get('series_upper', 'STM32F4xx')
    device = info.get('device', 'stm32f407xx')
    series_lower = series_upper.lower()

    return f"""/**
 * {series_upper} HAL MSP (MCU Support Package)
 * Generated by rabber mcu_init v{VERSION}
 */
#include "{device}.h"

/**
 * @brief  Initialize the GPIO MSP.
 */
void HAL_GPIO_MspInit(GPIO_TypeDef *GPIOx)
{{
    if (GPIOx == GPIOC)
    {{
        __HAL_RCC_GPIOC_CLK_ENABLE();
    }}
}}

/**
 * @brief  Initialize the RCC MSP.
 */
void HAL_RCC_MspInit(void)
{{
    /* RCC clock is enabled in system_stm32f4xx.c */
}}
'''

# insert before create_template
r3 = find_func(text, 'create_template')
if r3:
    s, e, old = r3
    text = text[:s] + hal_templates + text[s:]
    print("[OK] HAL template helpers inserted")
else:
    print("[FAIL] create_template not found")

# ── 4. Replace create_template ──
r4 = find_func(text, 'create_template')
if r4:
    s, e, old = r4
    new_ct = '''def create_template(mcu: str, info: dict, force: bool = False, hal_mode: bool = True) -> str | None:
    """Create template files under repos/<MCU>/.
    If hal_mode is True, downloads the full STM32 HAL/CMSIS library from GitHub."""
    repos_root = resolve_repos_root()
    target_dir = os.path.join(repos_root, mcu.upper())
    upper = mcu.upper()
    series_upper = info.get('series_upper', 'STM32F4xx')
    device = info.get('device', 'stm32f407xx')
    series_lower = series_upper.lower()

    if os.path.exists(target_dir):
        if not force:
            print(f"[!] 目录已存在: {target_dir}")
            print("    使用 --force 覆盖现有文件")
            return None
        print(f"[!] 覆盖现有目录: {target_dir}")

    if hal_mode:
        # Create HAL directory structure
        src_dir = os.path.join(target_dir, "Src")
        inc_dir = os.path.join(target_dir, "Inc")
        drivers_dir = os.path.join(target_dir, "Drivers")
        for d in [target_dir, src_dir, inc_dir, drivers_dir]:
            os.makedirs(d, exist_ok=True)

        # Download HAL/CMSIS library (extracts into target_dir/Drivers/)
        fetch_hal_library(mcu, info, target_dir)

        # Write project files
        files = {
            "Makefile": makefile_content(mcu, info, hal_mode=True),
            f"{upper}_FLASH.ld": linker_script_content(mcu, info),
            os.path.join("Src", "main.c"): main_c_hal_content(mcu, info),
            os.path.join("Inc", f"{series_lower}_hal_conf.h"): hal_conf_content(mcu, info),
            os.path.join("Inc", f"{series_lower}_it.h"): hal_it_header_content(mcu, info),
            os.path.join("Src", f"{series_lower}_it.c"): hal_it_content(mcu, info),
            os.path.join("Src", f"{series_lower}_hal_msp.c"): hal_msp_content(mcu, info),
        }
    else:
        # Bare-metal directory structure
        src_dir = os.path.join(target_dir, "src")
        inc_dir = os.path.join(target_dir, "include")
        for d in [target_dir, src_dir, inc_dir]:
            os.makedirs(d, exist_ok=True)

        files = {
            "Makefile": makefile_content(mcu, info, hal_mode=False),
            f"{upper}_FLASH.ld": linker_script_content(mcu, info),
            os.path.join("src", "main.c"): main_c_bare_content(mcu, info),
        }

    for rel_path, content in files.items():
        abs_path = os.path.join(target_dir, rel_path)
        os.makedirs(os.path.dirname(abs_path), exist_ok=True)
        with open(abs_path, "w") as f:
            f.write(content)
        print(f"  [✓] {rel_path}")

    mode_str = "HAL" if hal_mode else "bare-metal"
    print(f"\\n[✓] {mode_str} 模板创建完成: {target_dir}")
    if hal_mode:
        print(f"    进入目录后执行 'make' 编译")
    else:
        print(f"    进入目录后执行 'make' 编译")
        print(f"    或使用 'mcu_init init {mcu} --hal' 创建 HAL 模板")

    return target_dir
'''
    text = text[:s] + new_ct + text[e:]
    print("[OK] create_template replaced")
else:
    print("[FAIL] create_template not found (2nd pass)")

# ── 5. Replace action_init ──
r5 = find_func(text, 'action_init')
if r5:
    s, e, old = r5
    new_ai = '''def action_init(args: argparse.Namespace) -> None:
    """Handle the 'init' action."""
    extra = getattr(args, 'extra', []) or []
    extra = [a for a in extra if a != '--']
    force = "--force" in extra
    hal_mode = "--bare" not in extra  # default to HAL unless --bare
    mcu_input = " ".join([a for a in extra if not a.startswith("--")]) if extra else ""

    if not mcu_input:
        print("[!] 请指定 MCU 型号")
        print("用法: mcu_init init <MCU型号> [--hal|--bare] [--force]")
        print("示例: mcu_init init stm32f407zgt6")
        print("      mcu_init init stm32f407zgt6 --bare   (bare-metal, no HAL)")
        sys.exit(1)

    model = select_mcu(mcu_input)
    if model is None:
        sys.exit(1)

    info = MCU_DATABASE[model]
    if hal_mode:
        print(f"\\n[*] 模式: HAL 库 (将从 GitHub 下载 STM32Cube 包)")
    else:
        print(f"\\n[*] 模式: Bare-metal (纯寄存器操作, 无需 HAL)")

    target = create_template(model, info, force=force, hal_mode=hal_mode)

    if target:
        print(f"__RABBER_CD__:{target}")
    else:
        sys.exit(1)
'''
    text = text[:s] + new_ai + text[e:]
    print("[OK] action_init replaced")
else:
    print("[FAIL] action_init not found")

# ── Write back ──
with open(PATH, "w") as f:
    f.write(text)

print(f"\\nDone. File size: {len(text)} chars")
